SHOW DATABASES; -- TO LIST ALL THE DATA BASES

CREATE DATABASE NEWDATABASE; -- TO CREATE A DATA BASE

DROP DATABASE NEWDATABASE; -- TO DELETE ENTIER DATABASE
DROP SCHEMA NEWDATABASE; -- TO DELETE ENTIER DATABASE

DROP DATABASE IF EXISTS NEWDATABASE; -- IT IS USED TO DELETE THE DATA

-- x------------x-----------x--------------------x------------------x------------

USE SYS; -- "USE" IS USED TO "CHOOSE" THE DATABASE 
SHOW TABLES; -- USED TO DISPLAY THE TABLES IN THE DATABASE

-- x------------x-----------x--------------------x------------------x------------

USE NEWDATABASE;

CREATE TABLE TEST (
	Id INT PRIMARY KEY,
    Name VARCHAR(20),
    GPA DECIMAL(3,2)
);

DESCRIBE TEST; -- USED TO SHOW AND DESCRIBE THE TABLE 

DROP TABLE TEST;

-- "ALTER" IS USED TO DO CHANGE IN THE EXISTING TABLE 
ALTER TABLE TEST ADD Department VARCHAR(20); -- USED TO ADD COLUMN IN THE TABLE
ALTER TABLE TEST DROP Department; -- USED TO DELETE A COLUMN IN THE TABLE

INSERT INTO TEST
VALUE(1,'YOGA PRASANTH',9.3,'CSD'),
(2,'PRIYA',9.51,'ECE'),
(3,'ARUN',8.34,'CSD'),
(4,'KUMAR',8.84,'CSD');

INSERT INTO TEST(Id,Name,GPA) -- IT IS USED TO SET THE VALUES TO A SPECIFIC ROW
VALUES(5,'KISHORE',8.9);

SELECT * 
FROM TEST

